---

- name: Patch certain packages for demo purposes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - kernel
    - dhclient
  register: patches

- name: Downgrade sudo for demo purposes
  yum:
    name: sudo-1.8.6p7-21.el7_3.x86_64
    state: present
    allow_downgrade: true

- name: Reboot server
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: patches is changed

- name: Wait for server to come back
  wait_for: 
    host: "{{ inventory_hostname }}"
    delay: 10 
    timeout: 300 
    port: 22
  delegate_to: localhost
  when: patches is changed
