---

- name: Auth to RHV
  ovirt_auth:
    url: "{{ auth_url }}"
    username: "{{ username }}"
    password: "{{ password }}"
    insecure: true
  delegate_to: "{{ rhv_man }}"

- name: Create VM from template
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: running
    name: "{{ vm_name }}"
    template: "{{ cluster }}-{{ vm_template }}"
    cpu_cores: "{{ cpu_cores }}"
    memory: "{{ memory }}"
    cluster: "{{ cluster }}"
    operating_system: rhel_7x64
    comment: "{{ tower_user_name }}"
    cloud_init:
      host_name: "{{ vm_name }}"
      custom_script: |
        ssh_pwauth: True
        timezone: "Europe/London"
      user_name: root
      root_password: "{{ root_password }}"
      authorized_ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5nSv7U/yKr6murmlRh6QNSlEa0yjY6LveV52+53LSQoUBtMZVTiM3q2HA50TLglwb4TXBeVm8509IcG2EqFETaHeCasySEcbyM2yj93djvCUf6w79ojLI38oh902SqX/zLyFqAOlz4A140q3hrVqnsNKevT2I+jbnGNWBrSYhgOrsXbiu4RCcfPSeFLsaWPG/ECcjn+Sbu7kbDA9Ep66xaXd5c3he+nAiZXhTDBUvS7W6lurHuWxAUVoou7XSsAtVcx94AN236vJLxmFSLwiWFpQtIEKhRvIJSW1hgDZzfCsQFoFcxdQzlxxcfPnDnzyuK7bT/9eaEJ9mnb+u71o9 root@tower.demolab.local
    nics:
      - name: eth0
        profile_name: "{{ nic_profile }}"
  delegate_to: "{{ rhv_man }}"
