- name: Install firewalld
  yum:
    name: firewalld
    state: latest
  become: yes

- name: Install Ansible Python 2 Dependencies
  yum:
    name: python-firewall
    state: latest
  become: yes

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: running
    enabled: True
  become: yes
    