- name: Install firewalld
  yum:
    name: firewalld
    state: latest
  become: yes

- name: Install Ansible Python 2 Dependencies
  yum:
    name: python-firewall
    state: latest
  become: yes

- name: Start the firewall that Patrick thinks he removed!
  service:
    name: firewalld
    state: started
    enabled: True
  become: yes
    
